### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by petermorlion** [solvsoftware/Ghost-Azure#17]
Hello, could you check if the deployment to Azure still works for you? It doesn't for me. I first [contacted Microsoft](https://social.msdn.microsoft.com/Forums/en-US/6dd881b3-30a2-4803-b03d-1f73d8a46358/deploy-to-azure-for-ghost-blog-doesnt-work?forum=windowsazurewebsitespreview), but they tell me to post an issue in this repo. They also point me to the Ghost product in the Azure marketplace, but that isn't the up-to-date version.

**Comment by johnmeredith** [comment]
I get a "Missing Registration For Location or re-register provider for this location" error when autodeploying from the script. 

If I manually try, I get this in the log:

```Selected npm version 5.6.0
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: 'azuredeploy.json'
Copying file: 'config.development.json'
Copying file: 'config.production.json'
Copying file: 'db.js'
Copying file: 'entry.js'
Copying file: 'Gruntfile.js'
Copying file: 'iisnode.yml'
Copying file: 'index.js'
Copying file: 'LICENSE'
Copying file: 'MigratorConfig.js'
Copying file: 'package.json'
Copying file: 'PRIVACY.md'
Copying file: 'README.md'
Copying file: 'yarn.lock'
Copying file: 'content\adapters\README.md'
Copying file: 'content\apps\README.md'
Copying file: 'content\data\README.md'
Copying file: 'content\images\README.md'
Copying file: 'content\logs\README.md'
Copying file: 'content\themes\casper\author.hbs'
Copying file: 'content\themes\casper\default.hbs'
Copying file: 'content\themes\casper\error-404.hbs'
Copying file: 'content\themes\casper\error.hbs'
Copying file: 'content\themes\casper\gulpfile.js'
Copying file: 'content\themes\casper\index.hbs'
Copying file: 'content\themes\casper\LICENSE'
Copying file: 'content\themes\casper\package.json'
Copying file: 'content\themes\casper\page.hbs'
Copying file: 'content\themes\casper\post.hbs'
Copying file: 'content\themes\casper\README.md'
Copying file: 'content\themes\casper\tag.hbs'
Copying file: 'content\themes\casper\assets\screenshot-desktop.jpg'
Copying file: 'content\themes\casper\assets\screenshot-mobile.jpg'
Copying file: 'content\themes\casper\assets\built\global.css'
Copying file: 'content\themes\casper\assets\built\global.css.map'
Copying file: 'content\themes\casper\assets\built\screen.css'
Copying file: 'content\themes\casper\assets\built\screen.css.map'
Copying file: 'content\themes\casper\assets\css\.csscomb.json'
Copying file: 'content\themes\casper\assets\css\csscomb.json'
Copying file: 'content\themes\casper\assets\css\global.css'
Copying file: 'content\themes\casper\assets\css\screen.css'
Copying file: 'content\themes\casper\assets\js\infinitescroll.js'
Copying file: 'content\themes\casper\assets\js\jquery.fitvids.js'
Copying file: 'content\themes\casper\partials\floating-header.hbs'
Copying file: 'content\themes\casper\partials\post-card.hbs'
Copying file: 'content\themes\casper\partials\site-nav.hbs'
Copying file: 'content\themes\casper\partials\icons\facebook.hbs'
Copying file: 'content\themes\casper\partials\icons\ghost-logo.hbs'
Omitting next output lines...
Using start-up script index.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4.
Selected node.js version 8.9.4. Use package.json file to choose a different version.
Selected npm version 5.6.0
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN deprecated nodemailer@0.7.1: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
Thread was being aborted.
Thread was being aborted.
```
Now I get further if i open a console and manually `npm install`. But when I run `node db.js` is get this:

```npm install sqlite3 --save
Error: Cannot find module 'D:\home\site\wwwroot\node_modules\sqlite3\lib\binding\node-v57-win32-ia32\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (D:\home\site\wwwroot\node_modules\knex\lib\dialects\sqlite3\index.js:75:12)
    at Client_SQLite3.initializeDriver (D:\home\site\wwwroot\node_modules\knex\lib\client.js:219:26)
    at Client_SQLite3.Client (D:\home\site\wwwroot\node_modules\knex\lib\client.js:113:10)
    at new Client_SQLite3 (D:\home\site\wwwroot\node_modules\knex\lib\dialects\sqlite3\index.js:58:20)```

**Comment by johnmeredith** [comment]
OK - correction. The deployment will fail for specific Azure regions. South Central US works fine.

**Comment by petermorlion** [comment]
@johnmeredith I think you're having a different issue. I can't even get the azuredeploy.net site to work anymore. Though I see now that it works at my work, but not at home. Might be an issue with my user. I'll have to investigate further.

**Comment by RadoslavGatev** [comment]
Hey, 
I just tried deploying this via azuredeploy.net to West Europe and it succeeded. The blog works fine after I rebuild the NPM packages against the new version and set up the database.
Are you still having issues with it?

@petermorlion I recall having similar issues with azuredeploy.net which were caused by my login. I think it failed to populate my subscriptions and I was blocked from there on. I cannot recall in details how I fixed it but I was so close to contact Microsoft.

**Comment by johnmeredith** [comment]
Hi there, 
I did get it working - yes. But it was dependant on the region for me. Interesting that West Europe was working as I tried that. Having said that, I am using the free tier so not sure if this has an impact? 

My blog is up and is beautiful... thanks for your efforts guys. https://www.archetextur.es/

**Comment by petermorlion** [comment]
It seems to be fixed for me now. I also read about login issues but never could seem to fix it at that time. Currently, it works for me, so either my login/cookies/whatever issue magically resolved itself, or someone pushed some button :)
